---
default_language_version:
    python: python3.12

default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.2
    hooks:
      - id: check-github-workflows
        stages: [pre-commit, pre-merge-commit, manual]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
      - id: python-safety-dependencies-check
        files: pyproject.toml
        args: ["--groups=dev,main", --short-report]
        stages: [manual]

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
      - id: gitlint-ci

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - # noinspection SpellCheckingInspection
        id: gitleaks
        stages: [pre-commit, pre-merge-commit, manual]

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.2
    hooks:
      - id: poetry-check
        name: check poetry config in pyproject.toml is valid
        args: [--no-interaction]
        stages: [pre-commit, pre-merge-commit, manual]

      - id: poetry-check
        name: check poetry.lock file is valid
        args: [--lock, --no-interaction]
        stages: [pre-commit, pre-merge-commit, manual]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer

      - id: check-json
        stages: [pre-commit, pre-merge-commit, manual]

      - id: check-yaml
        stages: [pre-commit, pre-merge-commit, manual]

      - id: check-toml
        stages: [pre-commit, pre-merge-commit, manual]

      - id: check-xml
        stages: [pre-commit, pre-merge-commit, manual]

      - id: check-symlinks
        stages: [pre-commit, pre-merge-commit, manual]

      - id: check-merge-conflict
        stages: [pre-commit, pre-merge-commit, manual]

      - id: check-vcs-permalinks
        stages: [pre-commit, pre-merge-commit, manual]

      - id: destroyed-symlinks
        stages: [pre-commit, pre-merge-commit, manual]

      - id: check-case-conflict
        stages: [pre-commit, pre-merge-commit, manual]

      - id: check-ast
        stages: [pre-commit, pre-merge-commit, manual]

      - id: detect-private-key
        stages: [pre-commit, pre-merge-commit, manual]

      - id: fix-byte-order-marker
        stages: [pre-commit, pre-merge-commit, manual]

      - id: fix-encoding-pragma
        stages: [pre-commit, pre-merge-commit, manual]
        args: [--remove]

      - id: name-tests-test
        stages: [pre-commit, pre-merge-commit, manual]
        args: [--unittest]

      - id: pretty-format-json
        stages: [pre-commit, pre-merge-commit, manual]
        args: [--autofix]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
        stages: [pre-commit, pre-merge-commit, manual]

      - id: python-check-blanket-type-ignore
        stages: [pre-commit, pre-merge-commit, manual]

      - id: python-no-eval
        stages: [pre-commit, pre-merge-commit, manual]

      - id: python-no-log-warn
        stages: [pre-commit, pre-merge-commit, manual]

      - id: python-use-type-annotations
        stages: [pre-commit, pre-merge-commit, manual]
