= CCFT-PyMarkdown
Matthew Norton <matt@carrotmanmatt.com>
v2.0, 27/12/2024

:docinfodir: .asciidoctor
:docinfo: shared
:project-root: .

:!example-caption:
:!table-caption:
:icons: font
:experimental:

:_url-github: https://github.com
:_url-wikipedia: https://wikipedia.org/wiki
:_url-pypi: https://pypi.org

:url-project-repository: {_url-github}/CarrotManMatt/CCFT-PyMarkdown
:url-project-pypi: {_url-pypi}/project/CCFT-PyMarkdown
:url-mypy-home: https://mypy-lang.org
:url-mypy: {url-mypy-home}
:url-uv-home: https://astral.sh/uv
:url-uv: {url-uv-home}
:url-ruff-home: https://ruff.rs
:url-ruff: {url-ruff-home}
:url-python-home: https://python.org
:url-python: {url-python-home}
:url-python-download: {url-python-home}/downloads
:url-wiki-markdown: {_url-wikipedia}/Markdown
:url-pymarkdown-repository: {_url-github}/jackdewinter/pymarkdown
:url-pymarkdown: {url-pymarkdown-repository}
:url-profile-jackdewinter: {_url-github}/jackdewinter

:labelled-url-wiki-markdown: {url-wiki-markdown}[MarkDown]
:labelled-url-pymarkdown: {url-pymarkdown}[PyMarkdown]
:labelled-url-python: {url-python}[Python]
:labelled-url-profile-jackdewinter: {url-profile-jackdewinter}[jackdewinter]

image:https://img.shields.io/badge/%F0%9F%A5%95-CCFT--PyMarkdown-blue[CCFT-PyMarkdown,link={url-project-repository}]
image:https://img.shields.io/pypi/v/CCFT-PyMarkdown[PyPI Version,link={url-project-pypi}]
image:https://img.shields.io/pypi/pyversions/CCFT-PyMarkdown?logo=Python&logoColor=white&label=Python[Python Version,link={url-python-download}]
image:https://img.shields.io/endpoint?url=https://toml-version-extractor.carrotmanmatt.com/uv/CarrotManMatt/CCFT-PyMarkdown&logo=Markdown&label=PyMarkdown[PyMarkdown Version,link={url-pymarkdown}]
image:{url-project-repository}/actions/workflows/check-build-publish.yaml/badge.svg[Tests Status,link={url-project-repository}/actions/workflows/check-build-publish.yaml]
image:https://img.shields.io/badge/mypy-checked-%232EBB4E&label=mypy[mypy Status,link={url-mypy}]
image:https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/astral-sh/ruff/main/assets/badge/v2.json[Ruff,link={url-ruff}]
image:https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/astral-sh/uv/main/assets/badge/v0.json[uv,link={url-uv}]

****
A {labelled-url-python} wrapper around {labelled-url-profile-jackdewinter}'s {labelled-url-pymarkdown} linter to suppress errors, caused by custom-formatted tables in Markdown files
****

When running {labelled-url-pymarkdown} it may incorrectly flag errors inside a table that has correct formatting.
Using this wrapper, the errors will be suppressed by temporarily cleaning any custom-formatted tables.

== Usage

If you require sending additional arguments to the `+pymarkdown+` command you must <<manually-cleaning-custom-formatted-tables,manually clean>> any custom-formatted tables and then <<manually-restoring-custom-formatted-tables,manually restore>> the {labelled-url-wiki-markdown} files.

=== Scanning All Files After Cleaning Custom-Formatted Tables

To perform linting using {labelled-url-pymarkdown}, after cleaning custom-formatted tables within any {labelled-url-wiki-markdown} files, use the `+scan-all+` action:

[source,bash]
ccft-pymarkdown scan-all

[#manually-cleaning-custom-formatted-tables]
=== Manually Cleaning Custom-Formatted Tables

To manually clean custom-formatted-tables within any {labelled-url-wiki-markdown} files without running {labelled-url-pymarkdown}, use the `+clean+` action:

[source,bash]
ccft-pymarkdown clean

[#manually-restoring-custom-formatted-tables]
=== Manually Restoring {labelled-url-wiki-markdown} Files

To manually restore any {labelled-url-wiki-markdown} files without running {labelled-url-pymarkdown}, use the `+restore+` action:

[source,bash]
ccft-pymarkdown restore
