= CCFT-PyMarkdown
Matthew Norton <matt@carrotmanmatt.com>
v2.1, 26/01/2025

:docinfodir: .asciidoctor
:docinfo: shared
:project-root: .

:!example-caption:
:!table-caption:
:icons: font
:experimental:

:_url-github: https://github.com
:_url-wikipedia: https://wikipedia.org/wiki
:_url-pypi: https://pypi.org

:url-project-repository: {_url-github}/CarrotManMatt/CCFT-PyMarkdown
:url-project-pypi: {_url-pypi}/project/CCFT-PyMarkdown
:url-project-bug-tracker: {url-project-repository}/issues
:url-mypy-home: https://mypy-lang.org
:url-mypy: {url-mypy-home}
:url-uv-home: https://astral.sh/uv
:url-uv: {url-uv-home}
:url-ruff-home: https://ruff.rs
:url-ruff: {url-ruff-home}
:url-python-home: https://python.org
:url-python: {url-python-home}
:url-python-download: {url-python-home}/downloads
:url-python-wiki: https://docs.python.org/3
:url-python-wiki-virtual-environments: {url-python-wiki}/tutorial/venv
:url-python-packaging-wiki: https://packaging.python.org
:url-python-packaging-wiki-dependency-extras: {url-python-packaging-wiki}/specifications/dependency-specifiers#extras
:url-wiki-markdown: {_url-wikipedia}/Markdown
:url-pymarkdown-repository: {_url-github}/jackdewinter/pymarkdown
:url-pymarkdown: {url-pymarkdown-repository}
:url-profile-jackdewinter: {_url-github}/jackdewinter
:url-uv-home: https://astral.sh/uv
:url-uv: {url-uv-home}
:url-uv-wiki: https://docs.astral.sh/uv
:url-uv-wiki-tools: {url-uv-wiki}/guides/tools
:url-uv-wiki-tools-installing: {url-uv-wiki-tools}#installing-tools
:url-uv-wiki-tools-upgrading: {url-uv-wiki-tools}#upgrading-tools
:url-uv-wiki-dependencies-adding: {url-uv-wiki}/concepts/projects#managing-dependencies
:url-pip-home: https://pip.pypa.io
:url-pip: {url-pip-home}

:labelled-url-wiki-markdown: {url-wiki-markdown}[MarkDown]
:labelled-url-pymarkdown: {url-pymarkdown}[PyMarkdown]
:labelled-url-python: {url-python}[Python]
:labelled-url-profile-jackdewinter: {url-profile-jackdewinter}[jackdewinter]
:labelled-url-pip: {url-pip}[pip]
:labelled-url-uv: {url-uv}[uv]

image:https://img.shields.io/badge/%F0%9F%A5%95-CCFT--PyMarkdown-blue[CCFT-PyMarkdown,link={url-project-repository}]
image:https://img.shields.io/pypi/v/CCFT-PyMarkdown[PyPI Version,link={url-project-pypi}]
image:https://img.shields.io/pypi/pyversions/CCFT-PyMarkdown?logo=Python&logoColor=white&label=Python[Python Version,link={url-python-download}]
image:https://img.shields.io/endpoint?url=https://toml-version-extractor.carrotmanmatt.com/lock/CarrotManMatt/CCFT-PyMarkdown&logo=Markdown&label=PyMarkdown[PyMarkdown Version,link={url-pymarkdown}]
image:{url-project-repository}/actions/workflows/check-build-publish.yaml/badge.svg[Tests Status,link={url-project-repository}/actions/workflows/check-build-publish.yaml]
image:https://img.shields.io/badge/mypy-checked-%232EBB4E&label=mypy[mypy Status,link={url-mypy}]
image:https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/astral-sh/ruff/main/assets/badge/v2.json[Ruff,link={url-ruff}]
image:https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/astral-sh/uv/main/assets/badge/v0.json[uv,link={url-uv}]

****
A {labelled-url-python} wrapper around {labelled-url-profile-jackdewinter}'s {labelled-url-pymarkdown} linter to suppress errors, caused by custom-formatted tables in Markdown files
****

When running {labelled-url-pymarkdown} it may incorrectly flag errors inside a table that has correct formatting.
Using this wrapper, the errors will be suppressed by temporarily cleaning any custom-formatted tables.

== Installation

.Run as a {url-uv-wiki-tools}[uv tool] (no installation necessary)
[source,bash]
uvx -- ccft-pymarkdown --help

.{url-uv-wiki-tools-installing}[Install permenantly as a uv tool]
[source,bash]
uv tool install CCFT-PyMarkdown

.Install using {labelled-url-pip} after {url-python-wiki-virtual-environments}[creating a virtual environment]
[source,bash]
path/to/venv/python -m pip install CCFT-PyMarkdown

=== The `+[git-python]+` {url-python-packaging-wiki-dependency-extras}[Extra]

This package can also be installed with the `+[git-python]+` {url-python-packaging-wiki-dependency-extras}[optional dependency].
This will allow the identification of hidden/excluded files to make use of your project's `+.gitignore+` file.

.Run as a {url-uv-wiki-tools}[uv tool] (no installation necessary)
[source,bash]
uvx --from CCFT-PyMarkdown[git-python] -- ccft-pymarkdown --help

.{url-uv-wiki-tools-installing}[Install permenantly as a uv tool]
[source,bash]
uv tool install CCFT-PyMarkdown[git-python]

.Install using {labelled-url-pip} after {url-python-wiki-virtual-environments}[creating a virtual environment]
[source,bash]
path/to/venv/python -m pip install CCFT-PyMarkdown[git-python]

== Usage

[WARNING]
--
These commands will only work correctly either after installation as a {url-uv-wiki-tools-installing}[permenant uv tool], or after activating a virtual environment with CCFT-PyMarkdown installed.
Replace the command name `+ccft-pymarkdown+` with `+uvx -- ccft-pymarkdown+`, to run any of the following commands in an ephemeral envrionment.
--

TIP: If you require sending additional arguments to the `+pymarkdown+` command you must <<manually-cleaning-custom-formatted-tables,manually clean>> any custom-formatted tables and then <<manually-restoring-custom-formatted-tables,manually restore>> the {labelled-url-wiki-markdown} files.

.Output the help message
[source,bash]
ccft-pymarkdown --help

.Run with increased verbosity
[source,bash]
ccft-pymarkdown <command> -v

.Run without any logging output (incompatible with the `+-v+` flag)
[source,bash]
ccft-pymarkdown <command> -q

.Output the current version number
[source,bash]
ccft-pymarkdown --version

=== Scanning All Files After Cleaning Custom-Formatted Tables

.To perform linting using {labelled-url-pymarkdown}, after cleaning custom-formatted tables within any {labelled-url-wiki-markdown} files, use the `+scan-all+` action
[source,bash]
ccft-pymarkdown scan-all

.Scan files according to your `+.gitignore+` file (Not available when the `+[git-python]+` extra is not installed)
[source,bash]
ccft-pymarkdown scan-all --with-git

.Scan files without ignoring any hidden/excluded files
[source,bash]
ccft-pymarkdown scan-all --no-git

[#manually-cleaning-custom-formatted-tables]
=== Manually Cleaning Custom-Formatted Tables

.To manually clean custom-formatted-tables within any {labelled-url-wiki-markdown} files without running {labelled-url-pymarkdown}, use the `+clean+` action
[source,bash]
ccft-pymarkdown clean MyNotes.md MyReport.md

.Clean a whole directory and additional files
[source,bash]
ccft-pymarkdown clean my-notes/ MyReport.md

.Clean a whole directory according to your .gitignore file (Not available when the [git-python] extra is not installed)
[source,bash]
ccft-pymarkdown clean --with-git my-notes/

.Clean a whole directory without ignoring any hidden/excluded files
[source,bash]
ccft-pymarkdown clean --no-git my-notes/

.Clean files without making any changes, only report what would have been changed
[source,bash]
ccft-pymarkdown clean --dry-run MyNotes.md MyReport.md

[#manually-restoring-custom-formatted-tables]
=== Manually Restoring {labelled-url-wiki-markdown} Files

.To manually restore any {labelled-url-wiki-markdown} files without running {labelled-url-pymarkdown}, use the `+restore+` action
[source,bash]
ccft-pymarkdown restore MyNotes.md MyReport.md

.Restore a whole directory and additional files
[source,bash]
ccft-pymarkdown restore my-notes/ MyReport.md

.Restore files without making any changes, only report what would have been changed
[source,bash]
ccft-pymarkdown restore --dry-run MyNotes.md MyReport.md
