name: Publish PyPI Redirects

"on":
    workflow_dispatch: ~

jobs:
    CCFT-PyMarkdownlnt-redirect:
        environment: redirect-publish-CCFT-PyMarkdownlnt
        permissions:
            id-token: write
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Install uv
              uses: astral-sh/setup-uv@v6

            - name: Build Package
              run: uv build --sdist
              working-directory: ./.pypi-redirects/CCFT-PyMarkdownlnt

            - name: Publish to PyPI
              run: uv publish
              working-directory: ./.pypi-redirects/CCFT-PyMarkdownlnt
