---
name: Tests

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]

jobs:
    pytest:
        runs-on: ubuntu-latest

        steps:
          - name: Install Python Project
            uses: CarrotManMatt/action-install-python-project@v2
            with:
                python-version: 3.12

          - name: Run Pytest
            run: poetry run pytest

    mypy:
        runs-on: ubuntu-latest

        steps:
          - name: Install Python Project
            uses: CarrotManMatt/action-install-python-project@v2
            with:
                python-version: 3.12

          - name: Run Mypy
            run: poetry run mypy .

    ruff:
        runs-on: ubuntu-latest

        steps:
          - name: Install Python Project
            uses: CarrotManMatt/action-install-python-project@v2
            with:
                python-version: 3.12

          - name: Run Ruff
            run: poetry run ruff check . --no-fix --extend-select TD002,TD003

    poetry-check:
        runs-on: ubuntu-latest

        steps:
          - name: Install Python Project
            uses: CarrotManMatt/action-install-python-project@v2
            with:
                python-version: 3.12

          - name: Run poetry check
            run: poetry check --no-interaction --lock && poetry check --no-interaction

    yamllint:
        runs-on: ubuntu-latest

        steps:
          - name: Install Python Project
            uses: CarrotManMatt/action-install-python-project@v2
            with:
                python-version: 3.12

#          - name: Run yamllint
#            run: poetry run yamllint .  # TODO: Run with custom conversion from pyproject.toml

    asciidoctor:
        runs-on: ubuntu-latest

        steps:
          - name: Install AsciiDoctor
            run: apt-get update -y && apt-get install -y --no-install-recommends asciidoctor

          - name: Run AsciiDoctor
            run: asciidoctor -v --failure-level=WARNING -w -o /dev/null README.adoc
