---
name: Tests

"on":
    pull_request:
        branches: [main]
    push:
        branches: [main]

jobs:  # yamllint disable-line rule:key-ordering
    asciidoctor:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Install Asciidoctor
              run: sudo apt-get update -y &&
                   sudo apt-get install -y --no-install-recommends asciidoctor

            - name: Run Asciidoctor
              run: asciidoctor -v --failure-level=WARNING -w -o /dev/null README.adoc

    mypy:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12

            - name: Run mypy
              run: poetry run mypy .

    pytest:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12

            - name: Run Pytest
              run: poetry run pytest

    ruff:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12

            - name: Run Ruff
              run: poetry run ruff check --no-fix

    yamllint:
        runs-on: ubuntu-latest

        steps:
            - name: Install Python Project
              uses: CarrotManMatt/action-install-python-project@v2
              with:
                  python-version: 3.12

            - name: Run yamllint
              run: poetry run yamllint . -s -f colored
